// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace UnitTestProject1
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// UI unit test
        /// </summary>
        public void GuiaplikacijaUItest1()
        {
            #region Variable Declarations
            WinButton uIButton1Button = this.UIForm1Window.UIButton1Window.UIButton1Button;
            WinButton uIButton1Button1 = this.UIAdminstartWindow.UIButton1Window.UIButton1Button;
            WinButton uICloseButton = this.UIAdminSerijaWindow.UIAdminSerijaTitleBar.UICloseButton;
            WinButton uIButton2Button = this.UIAdminstartWindow.UIButton2Window.UIButton2Button;
            WinButton uICloseButton1 = this.UIAdminglumciWindow.UIAdminglumciTitleBar.UICloseButton;
            WinButton uIButton3Button = this.UIAdminstartWindow.UIButton3Window.UIButton3Button;
            WinButton uICloseButton2 = this.UIAdminosobljeWindow.UIAdminosobljeTitleBar.UICloseButton;
            WinButton uIButton4Button = this.UIAdminstartWindow.UIButton4Window.UIButton4Button;
            WinButton uICloseButton3 = this.UIAdminKlSerijaWindow.UIAdminKlSerijaTitleBar.UICloseButton;
            WinButton uICloseButton4 = this.UIAdminstartWindow.UIAdminstartTitleBar.UICloseButton;
            WinButton uIButton2Button1 = this.UIForm1Window.UIButton2Window.UIButton2Button;
            WinButton uIButton1Button2 = this.UIModstartWindow.UIButton1Window.UIButton1Button;
            WinButton uICloseButton5 = this.UIModSerijaWindow.UIModSerijaTitleBar.UICloseButton;
            WinButton uIButton2Button2 = this.UIModstartWindow.UIButton2Window.UIButton2Button;
            WinButton uICloseButton6 = this.UIModosobljeWindow.UIModosobljeTitleBar.UICloseButton;
            WinButton uIButton3Button1 = this.UIModstartWindow.UIButton3Window.UIButton3Button;
            WinButton uICloseButton7 = this.UIMOdglumciWindow.UIMOdglumciTitleBar.UICloseButton;
            WinButton uICloseButton8 = this.UIModstartWindow.UIModstartTitleBar.UICloseButton;
            WinButton uIButton3Button2 = this.UIForm1Window.UIButton3Window.UIButton3Button;
            WinButton uIButton1Button3 = this.UIKlijentstartWindow.UIButton1Window.UIButton1Button;
            WinButton uICloseButton9 = this.UIKlijentserijaklijentWindow.UIKlijentserijaklijentTitleBar.UICloseButton;
            WinButton uIButton2Button3 = this.UIKlijentstartWindow.UIButton2Window.UIButton2Button;
            WinButton uICloseButton10 = this.UIForm2Window.UIForm2TitleBar.UICloseButton;
            WinButton uICloseButton11 = this.UIKlijentstartWindow.UIKlijentstartTitleBar.UICloseButton;
            #endregion

            // Click 'button1' button
            Mouse.Click(uIButton1Button, new Point(16, 10));

            // Click 'button1' button
            Mouse.Click(uIButton1Button1, new Point(47, 16));

            // Click 'Close' button
            Mouse.Click(uICloseButton, new Point(12, 14));

            // Click 'button2' button
            Mouse.Click(uIButton2Button, new Point(52, 9));

            // Click 'Close' button
            Mouse.Click(uICloseButton1, new Point(21, 14));

            // Click 'button3' button
            Mouse.Click(uIButton3Button, new Point(42, 14));

            // Click 'Close' button
            Mouse.Click(uICloseButton2, new Point(16, 8));

            // Click 'button4' button
            Mouse.Click(uIButton4Button, new Point(47, 10));

            // Click 'Close' button
            Mouse.Click(uICloseButton3, new Point(23, 1));

            // Click 'Close' button
            Mouse.Click(uICloseButton4, new Point(12, 10));

            // Click 'button2' button
            Mouse.Click(uIButton2Button1, new Point(55, 11));

            // Click 'button1' button
            Mouse.Click(uIButton1Button2, new Point(26, 9));

            // Click 'Close' button
            Mouse.Click(uICloseButton5, new Point(15, 9));

            // Click 'button2' button
            Mouse.Click(uIButton2Button2, new Point(47, 13));

            // Click 'Close' button
            Mouse.Click(uICloseButton6, new Point(25, 12));

            // Click 'button3' button
            Mouse.Click(uIButton3Button1, new Point(54, 11));

            // Click 'Close' button
            Mouse.Click(uICloseButton7, new Point(5, 11));

            // Click 'Close' button
            Mouse.Click(uICloseButton8, new Point(15, 15));

            // Click 'button3' button
            Mouse.Click(uIButton3Button2, new Point(61, 7));

            // Click 'button1' button
            Mouse.Click(uIButton1Button3, new Point(39, 15));

            // Click 'Close' button
            Mouse.Click(uICloseButton9, new Point(10, 13));

            // Click 'button2' button
            Mouse.Click(uIButton2Button3, new Point(5, 8));

            // Click 'Close' button
            Mouse.Click(uICloseButton10, new Point(10, 15));

            // Click 'Close' button
            Mouse.Click(uICloseButton11, new Point(22, 13));
        }
        
        /// <summary>
        /// KlijentUIstarttest
        /// </summary>
        public void KlijentUIstarttest()
        {
            #region Variable Declarations
            WinButton uIButton3Button = this.UIForm1Window.UIButton3Window.UIButton3Button;
            WinButton uICloseButton = this.UIKlijentstartWindow.UIKlijentstartTitleBar.UICloseButton;
            #endregion

            // Click 'button3' button
            Mouse.Click(uIButton3Button, new Point(34, 10));

            // Click 'Close' button
            Mouse.Click(uICloseButton, new Point(16, 7));
        }
        
        /// <summary>
        /// KliKliseUItest
        /// </summary>
        public void KliKliseUItest()
        {

            // Last mouse action was not recorded.
        }
        
        /// <summary>
        /// KliseUITest
        /// </summary>
        public void KliseUITest()
        {
            #region Variable Declarations
            WinButton uIButton2Button = this.UIKlijentstartWindow.UIButton2Window.UIButton2Button;
            #endregion

            // Click 'button2' button
            Mouse.Click(uIButton2Button, new Point(51, 9));
        }
        
        /// <summary>
        /// admstarttest
        /// </summary>
        public void admstarttest()
        {
            #region Variable Declarations
            WinButton uIButton1Button = this.UIForm1Window.UIButton1Window.UIButton1Button;
            WinButton uIButton1Button1 = this.UIAdminstartWindow.UIButton1Window.UIButton1Button;
            WinButton uICloseButton = this.UIAdminSerijaWindow.UIAdminSerijaTitleBar.UICloseButton;
            WinButton uIButton2Button = this.UIAdminstartWindow.UIButton2Window.UIButton2Button;
            WinButton uICloseButton1 = this.UIAdminglumciWindow.UIAdminglumciTitleBar.UICloseButton;
            WinButton uIButton3Button = this.UIAdminstartWindow.UIButton3Window.UIButton3Button;
            WinButton uICloseButton2 = this.UIAdminosobljeWindow.UIAdminosobljeTitleBar.UICloseButton;
            WinButton uIButton4Button = this.UIAdminstartWindow.UIButton4Window.UIButton4Button;
            WinButton uICloseButton3 = this.UIAdminKlSerijaWindow.UIAdminKlSerijaTitleBar.UICloseButton;
            #endregion

            // Click 'button1' button
            Mouse.Click(uIButton1Button, new Point(48, 14));

            // Click 'button1' button
            Mouse.Click(uIButton1Button1, new Point(64, 10));

            // Click 'Close' button
            Mouse.Click(uICloseButton, new Point(14, 13));

            // Click 'button2' button
            Mouse.Click(uIButton2Button, new Point(64, 11));

            // Click 'Close' button
            Mouse.Click(uICloseButton1, new Point(27, 14));

            // Click 'button3' button
            Mouse.Click(uIButton3Button, new Point(54, 7));

            // Click 'Close' button
            Mouse.Click(uICloseButton2, new Point(15, 1));

            // Click 'button4' button
            Mouse.Click(uIButton4Button, new Point(46, 11));

            // Click 'Close' button
            Mouse.Click(uICloseButton3, new Point(23, 5));
        }
        
        /// <summary>
        /// admtest
        /// </summary>
        public void admtest()
        {
            #region Variable Declarations
            WinButton uIButton1Button = this.UIForm1Window.UIButton1Window.UIButton1Button;
            #endregion

            // Click 'button1' button
            Mouse.Click(uIButton1Button, new Point(57, 15));
        }
        
        /// <summary>
        /// modstart
        /// </summary>
        public void modstart()
        {
            #region Variable Declarations
            WinButton uIButton2Button = this.UIForm1Window.UIButton2Window.UIButton2Button;
            #endregion

            // Click 'button2' button
            Mouse.Click(uIButton2Button, new Point(26, 13));
        }
        
        #region Properties
        public UIForm1Window UIForm1Window
        {
            get
            {
                if ((this.mUIForm1Window == null))
                {
                    this.mUIForm1Window = new UIForm1Window();
                }
                return this.mUIForm1Window;
            }
        }
        
        public UIAdminstartWindow UIAdminstartWindow
        {
            get
            {
                if ((this.mUIAdminstartWindow == null))
                {
                    this.mUIAdminstartWindow = new UIAdminstartWindow();
                }
                return this.mUIAdminstartWindow;
            }
        }
        
        public UIAdminSerijaWindow UIAdminSerijaWindow
        {
            get
            {
                if ((this.mUIAdminSerijaWindow == null))
                {
                    this.mUIAdminSerijaWindow = new UIAdminSerijaWindow();
                }
                return this.mUIAdminSerijaWindow;
            }
        }
        
        public UIAdminglumciWindow UIAdminglumciWindow
        {
            get
            {
                if ((this.mUIAdminglumciWindow == null))
                {
                    this.mUIAdminglumciWindow = new UIAdminglumciWindow();
                }
                return this.mUIAdminglumciWindow;
            }
        }
        
        public UIAdminosobljeWindow UIAdminosobljeWindow
        {
            get
            {
                if ((this.mUIAdminosobljeWindow == null))
                {
                    this.mUIAdminosobljeWindow = new UIAdminosobljeWindow();
                }
                return this.mUIAdminosobljeWindow;
            }
        }
        
        public UIAdminKlSerijaWindow UIAdminKlSerijaWindow
        {
            get
            {
                if ((this.mUIAdminKlSerijaWindow == null))
                {
                    this.mUIAdminKlSerijaWindow = new UIAdminKlSerijaWindow();
                }
                return this.mUIAdminKlSerijaWindow;
            }
        }
        
        public UIModstartWindow UIModstartWindow
        {
            get
            {
                if ((this.mUIModstartWindow == null))
                {
                    this.mUIModstartWindow = new UIModstartWindow();
                }
                return this.mUIModstartWindow;
            }
        }
        
        public UIModSerijaWindow UIModSerijaWindow
        {
            get
            {
                if ((this.mUIModSerijaWindow == null))
                {
                    this.mUIModSerijaWindow = new UIModSerijaWindow();
                }
                return this.mUIModSerijaWindow;
            }
        }
        
        public UIModosobljeWindow UIModosobljeWindow
        {
            get
            {
                if ((this.mUIModosobljeWindow == null))
                {
                    this.mUIModosobljeWindow = new UIModosobljeWindow();
                }
                return this.mUIModosobljeWindow;
            }
        }
        
        public UIMOdglumciWindow UIMOdglumciWindow
        {
            get
            {
                if ((this.mUIMOdglumciWindow == null))
                {
                    this.mUIMOdglumciWindow = new UIMOdglumciWindow();
                }
                return this.mUIMOdglumciWindow;
            }
        }
        
        public UIKlijentstartWindow UIKlijentstartWindow
        {
            get
            {
                if ((this.mUIKlijentstartWindow == null))
                {
                    this.mUIKlijentstartWindow = new UIKlijentstartWindow();
                }
                return this.mUIKlijentstartWindow;
            }
        }
        
        public UIKlijentserijaklijentWindow UIKlijentserijaklijentWindow
        {
            get
            {
                if ((this.mUIKlijentserijaklijentWindow == null))
                {
                    this.mUIKlijentserijaklijentWindow = new UIKlijentserijaklijentWindow();
                }
                return this.mUIKlijentserijaklijentWindow;
            }
        }
        
        public UIForm2Window UIForm2Window
        {
            get
            {
                if ((this.mUIForm2Window == null))
                {
                    this.mUIForm2Window = new UIForm2Window();
                }
                return this.mUIForm2Window;
            }
        }
        #endregion
        
        #region Fields
        private UIForm1Window mUIForm1Window;
        
        private UIAdminstartWindow mUIAdminstartWindow;
        
        private UIAdminSerijaWindow mUIAdminSerijaWindow;
        
        private UIAdminglumciWindow mUIAdminglumciWindow;
        
        private UIAdminosobljeWindow mUIAdminosobljeWindow;
        
        private UIAdminKlSerijaWindow mUIAdminKlSerijaWindow;
        
        private UIModstartWindow mUIModstartWindow;
        
        private UIModSerijaWindow mUIModSerijaWindow;
        
        private UIModosobljeWindow mUIModosobljeWindow;
        
        private UIMOdglumciWindow mUIMOdglumciWindow;
        
        private UIKlijentstartWindow mUIKlijentstartWindow;
        
        private UIKlijentserijaklijentWindow mUIKlijentserijaklijentWindow;
        
        private UIForm2Window mUIForm2Window;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIForm1Window : WinWindow
    {
        
        public UIForm1Window()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Form1";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public UIButton1Window UIButton1Window
        {
            get
            {
                if ((this.mUIButton1Window == null))
                {
                    this.mUIButton1Window = new UIButton1Window(this);
                }
                return this.mUIButton1Window;
            }
        }
        
        public UIButton2Window UIButton2Window
        {
            get
            {
                if ((this.mUIButton2Window == null))
                {
                    this.mUIButton2Window = new UIButton2Window(this);
                }
                return this.mUIButton2Window;
            }
        }
        
        public UIButton3Window UIButton3Window
        {
            get
            {
                if ((this.mUIButton3Window == null))
                {
                    this.mUIButton3Window = new UIButton3Window(this);
                }
                return this.mUIButton3Window;
            }
        }
        #endregion
        
        #region Fields
        private UIButton1Window mUIButton1Window;
        
        private UIButton2Window mUIButton2Window;
        
        private UIButton3Window mUIButton3Window;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIButton1Window : WinWindow
    {
        
        public UIButton1Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "button1";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinButton UIButton1Button
        {
            get
            {
                if ((this.mUIButton1Button == null))
                {
                    this.mUIButton1Button = new WinButton(this);
                    #region Search Criteria
                    this.mUIButton1Button.SearchProperties[WinButton.PropertyNames.Name] = "button1";
                    this.mUIButton1Button.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIButton1Button;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIButton1Button;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIButton2Window : WinWindow
    {
        
        public UIButton2Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "button2";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinButton UIButton2Button
        {
            get
            {
                if ((this.mUIButton2Button == null))
                {
                    this.mUIButton2Button = new WinButton(this);
                    #region Search Criteria
                    this.mUIButton2Button.SearchProperties[WinButton.PropertyNames.Name] = "button2";
                    this.mUIButton2Button.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIButton2Button;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIButton2Button;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIButton3Window : WinWindow
    {
        
        public UIButton3Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "button3";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinButton UIButton3Button
        {
            get
            {
                if ((this.mUIButton3Button == null))
                {
                    this.mUIButton3Button = new WinButton(this);
                    #region Search Criteria
                    this.mUIButton3Button.SearchProperties[WinButton.PropertyNames.Name] = "button3";
                    this.mUIButton3Button.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIButton3Button;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIButton3Button;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIAdminstartWindow : WinWindow
    {
        
        public UIAdminstartWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Adminstart";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Adminstart");
            #endregion
        }
        
        #region Properties
        public UIButton1Window1 UIButton1Window
        {
            get
            {
                if ((this.mUIButton1Window == null))
                {
                    this.mUIButton1Window = new UIButton1Window1(this);
                }
                return this.mUIButton1Window;
            }
        }
        
        public UIButton2Window1 UIButton2Window
        {
            get
            {
                if ((this.mUIButton2Window == null))
                {
                    this.mUIButton2Window = new UIButton2Window1(this);
                }
                return this.mUIButton2Window;
            }
        }
        
        public UIButton3Window1 UIButton3Window
        {
            get
            {
                if ((this.mUIButton3Window == null))
                {
                    this.mUIButton3Window = new UIButton3Window1(this);
                }
                return this.mUIButton3Window;
            }
        }
        
        public UIButton4Window UIButton4Window
        {
            get
            {
                if ((this.mUIButton4Window == null))
                {
                    this.mUIButton4Window = new UIButton4Window(this);
                }
                return this.mUIButton4Window;
            }
        }
        
        public UIAdminstartTitleBar UIAdminstartTitleBar
        {
            get
            {
                if ((this.mUIAdminstartTitleBar == null))
                {
                    this.mUIAdminstartTitleBar = new UIAdminstartTitleBar(this);
                }
                return this.mUIAdminstartTitleBar;
            }
        }
        #endregion
        
        #region Fields
        private UIButton1Window1 mUIButton1Window;
        
        private UIButton2Window1 mUIButton2Window;
        
        private UIButton3Window1 mUIButton3Window;
        
        private UIButton4Window mUIButton4Window;
        
        private UIAdminstartTitleBar mUIAdminstartTitleBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIButton1Window1 : WinWindow
    {
        
        public UIButton1Window1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "button1";
            this.WindowTitles.Add("Adminstart");
            #endregion
        }
        
        #region Properties
        public WinButton UIButton1Button
        {
            get
            {
                if ((this.mUIButton1Button == null))
                {
                    this.mUIButton1Button = new WinButton(this);
                    #region Search Criteria
                    this.mUIButton1Button.SearchProperties[WinButton.PropertyNames.Name] = "button1";
                    this.mUIButton1Button.WindowTitles.Add("Adminstart");
                    #endregion
                }
                return this.mUIButton1Button;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIButton1Button;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIButton2Window1 : WinWindow
    {
        
        public UIButton2Window1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "button2";
            this.WindowTitles.Add("Adminstart");
            #endregion
        }
        
        #region Properties
        public WinButton UIButton2Button
        {
            get
            {
                if ((this.mUIButton2Button == null))
                {
                    this.mUIButton2Button = new WinButton(this);
                    #region Search Criteria
                    this.mUIButton2Button.SearchProperties[WinButton.PropertyNames.Name] = "button2";
                    this.mUIButton2Button.WindowTitles.Add("Adminstart");
                    #endregion
                }
                return this.mUIButton2Button;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIButton2Button;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIButton3Window1 : WinWindow
    {
        
        public UIButton3Window1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "button3";
            this.WindowTitles.Add("Adminstart");
            #endregion
        }
        
        #region Properties
        public WinButton UIButton3Button
        {
            get
            {
                if ((this.mUIButton3Button == null))
                {
                    this.mUIButton3Button = new WinButton(this);
                    #region Search Criteria
                    this.mUIButton3Button.SearchProperties[WinButton.PropertyNames.Name] = "button3";
                    this.mUIButton3Button.WindowTitles.Add("Adminstart");
                    #endregion
                }
                return this.mUIButton3Button;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIButton3Button;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIButton4Window : WinWindow
    {
        
        public UIButton4Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "button4";
            this.WindowTitles.Add("Adminstart");
            #endregion
        }
        
        #region Properties
        public WinButton UIButton4Button
        {
            get
            {
                if ((this.mUIButton4Button == null))
                {
                    this.mUIButton4Button = new WinButton(this);
                    #region Search Criteria
                    this.mUIButton4Button.SearchProperties[WinButton.PropertyNames.Name] = "button4";
                    this.mUIButton4Button.WindowTitles.Add("Adminstart");
                    #endregion
                }
                return this.mUIButton4Button;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIButton4Button;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIAdminstartTitleBar : WinTitleBar
    {
        
        public UIAdminstartTitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Adminstart");
            #endregion
        }
        
        #region Properties
        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("Adminstart");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICloseButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIAdminSerijaWindow : WinWindow
    {
        
        public UIAdminSerijaWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "AdminSerija";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("AdminSerija");
            #endregion
        }
        
        #region Properties
        public UIAdminSerijaTitleBar UIAdminSerijaTitleBar
        {
            get
            {
                if ((this.mUIAdminSerijaTitleBar == null))
                {
                    this.mUIAdminSerijaTitleBar = new UIAdminSerijaTitleBar(this);
                }
                return this.mUIAdminSerijaTitleBar;
            }
        }
        #endregion
        
        #region Fields
        private UIAdminSerijaTitleBar mUIAdminSerijaTitleBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIAdminSerijaTitleBar : WinTitleBar
    {
        
        public UIAdminSerijaTitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("AdminSerija");
            #endregion
        }
        
        #region Properties
        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("AdminSerija");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICloseButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIAdminglumciWindow : WinWindow
    {
        
        public UIAdminglumciWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Adminglumci";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Adminglumci");
            #endregion
        }
        
        #region Properties
        public UIAdminglumciTitleBar UIAdminglumciTitleBar
        {
            get
            {
                if ((this.mUIAdminglumciTitleBar == null))
                {
                    this.mUIAdminglumciTitleBar = new UIAdminglumciTitleBar(this);
                }
                return this.mUIAdminglumciTitleBar;
            }
        }
        #endregion
        
        #region Fields
        private UIAdminglumciTitleBar mUIAdminglumciTitleBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIAdminglumciTitleBar : WinTitleBar
    {
        
        public UIAdminglumciTitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Adminglumci");
            #endregion
        }
        
        #region Properties
        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("Adminglumci");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICloseButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIAdminosobljeWindow : WinWindow
    {
        
        public UIAdminosobljeWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Adminosoblje";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Adminosoblje");
            #endregion
        }
        
        #region Properties
        public UIAdminosobljeTitleBar UIAdminosobljeTitleBar
        {
            get
            {
                if ((this.mUIAdminosobljeTitleBar == null))
                {
                    this.mUIAdminosobljeTitleBar = new UIAdminosobljeTitleBar(this);
                }
                return this.mUIAdminosobljeTitleBar;
            }
        }
        #endregion
        
        #region Fields
        private UIAdminosobljeTitleBar mUIAdminosobljeTitleBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIAdminosobljeTitleBar : WinTitleBar
    {
        
        public UIAdminosobljeTitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Adminosoblje");
            #endregion
        }
        
        #region Properties
        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("Adminosoblje");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICloseButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIAdminKlSerijaWindow : WinWindow
    {
        
        public UIAdminKlSerijaWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "AdminKlSerija";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("AdminKlSerija");
            #endregion
        }
        
        #region Properties
        public UIAdminKlSerijaTitleBar UIAdminKlSerijaTitleBar
        {
            get
            {
                if ((this.mUIAdminKlSerijaTitleBar == null))
                {
                    this.mUIAdminKlSerijaTitleBar = new UIAdminKlSerijaTitleBar(this);
                }
                return this.mUIAdminKlSerijaTitleBar;
            }
        }
        #endregion
        
        #region Fields
        private UIAdminKlSerijaTitleBar mUIAdminKlSerijaTitleBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIAdminKlSerijaTitleBar : WinTitleBar
    {
        
        public UIAdminKlSerijaTitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("AdminKlSerija");
            #endregion
        }
        
        #region Properties
        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("AdminKlSerija");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICloseButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIModstartWindow : WinWindow
    {
        
        public UIModstartWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Modstart";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Modstart");
            #endregion
        }
        
        #region Properties
        public UIButton1Window2 UIButton1Window
        {
            get
            {
                if ((this.mUIButton1Window == null))
                {
                    this.mUIButton1Window = new UIButton1Window2(this);
                }
                return this.mUIButton1Window;
            }
        }
        
        public UIButton2Window2 UIButton2Window
        {
            get
            {
                if ((this.mUIButton2Window == null))
                {
                    this.mUIButton2Window = new UIButton2Window2(this);
                }
                return this.mUIButton2Window;
            }
        }
        
        public UIButton3Window2 UIButton3Window
        {
            get
            {
                if ((this.mUIButton3Window == null))
                {
                    this.mUIButton3Window = new UIButton3Window2(this);
                }
                return this.mUIButton3Window;
            }
        }
        
        public UIModstartTitleBar UIModstartTitleBar
        {
            get
            {
                if ((this.mUIModstartTitleBar == null))
                {
                    this.mUIModstartTitleBar = new UIModstartTitleBar(this);
                }
                return this.mUIModstartTitleBar;
            }
        }
        #endregion
        
        #region Fields
        private UIButton1Window2 mUIButton1Window;
        
        private UIButton2Window2 mUIButton2Window;
        
        private UIButton3Window2 mUIButton3Window;
        
        private UIModstartTitleBar mUIModstartTitleBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIButton1Window2 : WinWindow
    {
        
        public UIButton1Window2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "button1";
            this.WindowTitles.Add("Modstart");
            #endregion
        }
        
        #region Properties
        public WinButton UIButton1Button
        {
            get
            {
                if ((this.mUIButton1Button == null))
                {
                    this.mUIButton1Button = new WinButton(this);
                    #region Search Criteria
                    this.mUIButton1Button.SearchProperties[WinButton.PropertyNames.Name] = "button1";
                    this.mUIButton1Button.WindowTitles.Add("Modstart");
                    #endregion
                }
                return this.mUIButton1Button;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIButton1Button;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIButton2Window2 : WinWindow
    {
        
        public UIButton2Window2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "button2";
            this.WindowTitles.Add("Modstart");
            #endregion
        }
        
        #region Properties
        public WinButton UIButton2Button
        {
            get
            {
                if ((this.mUIButton2Button == null))
                {
                    this.mUIButton2Button = new WinButton(this);
                    #region Search Criteria
                    this.mUIButton2Button.SearchProperties[WinButton.PropertyNames.Name] = "button2";
                    this.mUIButton2Button.WindowTitles.Add("Modstart");
                    #endregion
                }
                return this.mUIButton2Button;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIButton2Button;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIButton3Window2 : WinWindow
    {
        
        public UIButton3Window2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "button3";
            this.WindowTitles.Add("Modstart");
            #endregion
        }
        
        #region Properties
        public WinButton UIButton3Button
        {
            get
            {
                if ((this.mUIButton3Button == null))
                {
                    this.mUIButton3Button = new WinButton(this);
                    #region Search Criteria
                    this.mUIButton3Button.SearchProperties[WinButton.PropertyNames.Name] = "button3";
                    this.mUIButton3Button.WindowTitles.Add("Modstart");
                    #endregion
                }
                return this.mUIButton3Button;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIButton3Button;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIModstartTitleBar : WinTitleBar
    {
        
        public UIModstartTitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Modstart");
            #endregion
        }
        
        #region Properties
        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("Modstart");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICloseButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIModSerijaWindow : WinWindow
    {
        
        public UIModSerijaWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "ModSerija";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("ModSerija");
            #endregion
        }
        
        #region Properties
        public UIModSerijaTitleBar UIModSerijaTitleBar
        {
            get
            {
                if ((this.mUIModSerijaTitleBar == null))
                {
                    this.mUIModSerijaTitleBar = new UIModSerijaTitleBar(this);
                }
                return this.mUIModSerijaTitleBar;
            }
        }
        #endregion
        
        #region Fields
        private UIModSerijaTitleBar mUIModSerijaTitleBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIModSerijaTitleBar : WinTitleBar
    {
        
        public UIModSerijaTitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("ModSerija");
            #endregion
        }
        
        #region Properties
        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("ModSerija");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICloseButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIModosobljeWindow : WinWindow
    {
        
        public UIModosobljeWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Modosoblje";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Modosoblje");
            #endregion
        }
        
        #region Properties
        public UIModosobljeTitleBar UIModosobljeTitleBar
        {
            get
            {
                if ((this.mUIModosobljeTitleBar == null))
                {
                    this.mUIModosobljeTitleBar = new UIModosobljeTitleBar(this);
                }
                return this.mUIModosobljeTitleBar;
            }
        }
        #endregion
        
        #region Fields
        private UIModosobljeTitleBar mUIModosobljeTitleBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIModosobljeTitleBar : WinTitleBar
    {
        
        public UIModosobljeTitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Modosoblje");
            #endregion
        }
        
        #region Properties
        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("Modosoblje");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICloseButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIMOdglumciWindow : WinWindow
    {
        
        public UIMOdglumciWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "MOdglumci";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("MOdglumci");
            #endregion
        }
        
        #region Properties
        public UIMOdglumciTitleBar UIMOdglumciTitleBar
        {
            get
            {
                if ((this.mUIMOdglumciTitleBar == null))
                {
                    this.mUIMOdglumciTitleBar = new UIMOdglumciTitleBar(this);
                }
                return this.mUIMOdglumciTitleBar;
            }
        }
        #endregion
        
        #region Fields
        private UIMOdglumciTitleBar mUIMOdglumciTitleBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIMOdglumciTitleBar : WinTitleBar
    {
        
        public UIMOdglumciTitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("MOdglumci");
            #endregion
        }
        
        #region Properties
        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("MOdglumci");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICloseButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIKlijentstartWindow : WinWindow
    {
        
        public UIKlijentstartWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Klijentstart";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Klijentstart");
            #endregion
        }
        
        #region Properties
        public UIButton1Window3 UIButton1Window
        {
            get
            {
                if ((this.mUIButton1Window == null))
                {
                    this.mUIButton1Window = new UIButton1Window3(this);
                }
                return this.mUIButton1Window;
            }
        }
        
        public UIButton2Window3 UIButton2Window
        {
            get
            {
                if ((this.mUIButton2Window == null))
                {
                    this.mUIButton2Window = new UIButton2Window3(this);
                }
                return this.mUIButton2Window;
            }
        }
        
        public UIKlijentstartTitleBar UIKlijentstartTitleBar
        {
            get
            {
                if ((this.mUIKlijentstartTitleBar == null))
                {
                    this.mUIKlijentstartTitleBar = new UIKlijentstartTitleBar(this);
                }
                return this.mUIKlijentstartTitleBar;
            }
        }
        #endregion
        
        #region Fields
        private UIButton1Window3 mUIButton1Window;
        
        private UIButton2Window3 mUIButton2Window;
        
        private UIKlijentstartTitleBar mUIKlijentstartTitleBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIButton1Window3 : WinWindow
    {
        
        public UIButton1Window3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "button1";
            this.WindowTitles.Add("Klijentstart");
            #endregion
        }
        
        #region Properties
        public WinButton UIButton1Button
        {
            get
            {
                if ((this.mUIButton1Button == null))
                {
                    this.mUIButton1Button = new WinButton(this);
                    #region Search Criteria
                    this.mUIButton1Button.SearchProperties[WinButton.PropertyNames.Name] = "button1";
                    this.mUIButton1Button.WindowTitles.Add("Klijentstart");
                    #endregion
                }
                return this.mUIButton1Button;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIButton1Button;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIButton2Window3 : WinWindow
    {
        
        public UIButton2Window3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "button2";
            this.WindowTitles.Add("Klijentstart");
            #endregion
        }
        
        #region Properties
        public WinButton UIButton2Button
        {
            get
            {
                if ((this.mUIButton2Button == null))
                {
                    this.mUIButton2Button = new WinButton(this);
                    #region Search Criteria
                    this.mUIButton2Button.SearchProperties[WinButton.PropertyNames.Name] = "button2";
                    this.mUIButton2Button.WindowTitles.Add("Klijentstart");
                    #endregion
                }
                return this.mUIButton2Button;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIButton2Button;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIKlijentstartTitleBar : WinTitleBar
    {
        
        public UIKlijentstartTitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Klijentstart");
            #endregion
        }
        
        #region Properties
        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("Klijentstart");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICloseButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIKlijentserijaklijentWindow : WinWindow
    {
        
        public UIKlijentserijaklijentWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Klijentserijaklijent";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Klijentserijaklijent");
            #endregion
        }
        
        #region Properties
        public UIKlijentserijaklijentTitleBar UIKlijentserijaklijentTitleBar
        {
            get
            {
                if ((this.mUIKlijentserijaklijentTitleBar == null))
                {
                    this.mUIKlijentserijaklijentTitleBar = new UIKlijentserijaklijentTitleBar(this);
                }
                return this.mUIKlijentserijaklijentTitleBar;
            }
        }
        #endregion
        
        #region Fields
        private UIKlijentserijaklijentTitleBar mUIKlijentserijaklijentTitleBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIKlijentserijaklijentTitleBar : WinTitleBar
    {
        
        public UIKlijentserijaklijentTitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Klijentserijaklijent");
            #endregion
        }
        
        #region Properties
        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("Klijentserijaklijent");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICloseButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIForm2Window : WinWindow
    {
        
        public UIForm2Window()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Form2";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Form2");
            #endregion
        }
        
        #region Properties
        public UIForm2TitleBar UIForm2TitleBar
        {
            get
            {
                if ((this.mUIForm2TitleBar == null))
                {
                    this.mUIForm2TitleBar = new UIForm2TitleBar(this);
                }
                return this.mUIForm2TitleBar;
            }
        }
        #endregion
        
        #region Fields
        private UIForm2TitleBar mUIForm2TitleBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIForm2TitleBar : WinTitleBar
    {
        
        public UIForm2TitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Form2");
            #endregion
        }
        
        #region Properties
        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("Form2");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICloseButton;
        #endregion
    }
}
