<?xml version="1.0" encoding="utf-8"?><Database Name="AplikacijaBase" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\AplikacijaBase.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="AplikacijaGUI.Properties.Settings" SettingsPropertyName="AplikacijaBaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Serija" Member="Serijas">
    <Type Name="Serija">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Ime" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Glumci" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Osoblje" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Opis" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Serija_Klijent_serija" Member="Klijent_serija" ThisKey="ID" OtherKey="ID" Type="Klijent_serija" Cardinality="One" />
      <Association Name="Serija_Klijent_serija1" Member="Klijent_serijas" ThisKey="ID" OtherKey="IDserije" Type="Klijent_serija" />
      <Association Name="Osoblje_Serija" Member="Osoblje1" ThisKey="ID" OtherKey="ID" Type="Osoblje" IsForeignKey="true" />
      <Association Name="Glumci_Serija" Member="Glumci1" ThisKey="ID" OtherKey="ID" Type="Glumci" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Klijent_serija" Member="Klijent_serijas">
    <Type Name="Klijent_serija">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDserije" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ime" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Glumci" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Osoblje" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Opis" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Pogledano_epizoda" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Serija_Klijent_serija" Member="Serija" ThisKey="ID" OtherKey="ID" Type="Serija" IsForeignKey="true" />
      <Association Name="Serija_Klijent_serija1" Member="Serija1" ThisKey="IDserije" OtherKey="ID" Type="Serija" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Osoblje" Member="Osobljes">
    <Type Name="Osoblje">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Ime" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Prezime" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Tvrtka" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Osoblje_Serija" Member="Serija" ThisKey="ID" OtherKey="ID" Type="Serija" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.Glumci" Member="Glumcis">
    <Type Name="Glumci">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ime" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="prezime" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Glumci_Serija" Member="Serija" ThisKey="ID" OtherKey="ID" Type="Serija" Cardinality="One" />
    </Type>
  </Table>
</Database>