#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplikacijaGUI
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AplikacijaBase")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSerija(Serija instance);
    partial void UpdateSerija(Serija instance);
    partial void DeleteSerija(Serija instance);
    partial void InsertGlumci(Glumci instance);
    partial void UpdateGlumci(Glumci instance);
    partial void DeleteGlumci(Glumci instance);
    partial void InsertKlijent_serija(Klijent_serija instance);
    partial void UpdateKlijent_serija(Klijent_serija instance);
    partial void DeleteKlijent_serija(Klijent_serija instance);
    partial void InsertOsoblje(Osoblje instance);
    partial void UpdateOsoblje(Osoblje instance);
    partial void DeleteOsoblje(Osoblje instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::AplikacijaGUI.Properties.Settings.Default.AplikacijaBaseConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Serija> Serijas
		{
			get
			{
				return this.GetTable<Serija>();
			}
		}
		
		public System.Data.Linq.Table<Glumci> Glumcis
		{
			get
			{
				return this.GetTable<Glumci>();
			}
		}
		
		public System.Data.Linq.Table<Klijent_serija> Klijent_serijas
		{
			get
			{
				return this.GetTable<Klijent_serija>();
			}
		}
		
		public System.Data.Linq.Table<Osoblje> Osobljes
		{
			get
			{
				return this.GetTable<Osoblje>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Serija")]
	public partial class Serija : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Ime;
		
		private string _Glumci;
		
		private string _Osoblje;
		
		private string _Opis;
		
		private EntityRef<Klijent_serija> _Klijent_serija;
		
		private EntitySet<Klijent_serija> _Klijent_serijas;
		
		private EntityRef<Glumci> _Glumci1;
		
		private EntityRef<Osoblje> _Osoblje1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnImeChanging(string value);
    partial void OnImeChanged();
    partial void OnGlumciChanging(string value);
    partial void OnGlumciChanged();
    partial void OnOsobljeChanging(string value);
    partial void OnOsobljeChanged();
    partial void OnOpisChanging(string value);
    partial void OnOpisChanged();
    #endregion
		
		public Serija()
		{
			this._Klijent_serija = default(EntityRef<Klijent_serija>);
			this._Klijent_serijas = new EntitySet<Klijent_serija>(new Action<Klijent_serija>(this.attach_Klijent_serijas), new Action<Klijent_serija>(this.detach_Klijent_serijas));
			this._Glumci1 = default(EntityRef<Glumci>);
			this._Osoblje1 = default(EntityRef<Osoblje>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					if ((this._Glumci1.HasLoadedOrAssignedValue || this._Osoblje1.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ime", DbType="NVarChar(MAX)")]
		public string Ime
		{
			get
			{
				return this._Ime;
			}
			set
			{
				if ((this._Ime != value))
				{
					this.OnImeChanging(value);
					this.SendPropertyChanging();
					this._Ime = value;
					this.SendPropertyChanged("Ime");
					this.OnImeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Glumci", DbType="NVarChar(MAX)")]
		public string Glumci
		{
			get
			{
				return this._Glumci;
			}
			set
			{
				if ((this._Glumci != value))
				{
					this.OnGlumciChanging(value);
					this.SendPropertyChanging();
					this._Glumci = value;
					this.SendPropertyChanged("Glumci");
					this.OnGlumciChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Osoblje", DbType="NVarChar(MAX)")]
		public string Osoblje
		{
			get
			{
				return this._Osoblje;
			}
			set
			{
				if ((this._Osoblje != value))
				{
					this.OnOsobljeChanging(value);
					this.SendPropertyChanging();
					this._Osoblje = value;
					this.SendPropertyChanged("Osoblje");
					this.OnOsobljeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Opis", DbType="NVarChar(MAX)")]
		public string Opis
		{
			get
			{
				return this._Opis;
			}
			set
			{
				if ((this._Opis != value))
				{
					this.OnOpisChanging(value);
					this.SendPropertyChanging();
					this._Opis = value;
					this.SendPropertyChanged("Opis");
					this.OnOpisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Serija_Klijent_serija", Storage="_Klijent_serija", ThisKey="ID", OtherKey="ID", IsUnique=true, IsForeignKey=false)]
		public Klijent_serija Klijent_serija
		{
			get
			{
				return this._Klijent_serija.Entity;
			}
			set
			{
				Klijent_serija previousValue = this._Klijent_serija.Entity;
				if (((previousValue != value) 
							|| (this._Klijent_serija.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Klijent_serija.Entity = null;
						previousValue.Serija = null;
					}
					this._Klijent_serija.Entity = value;
					if ((value != null))
					{
						value.Serija = this;
					}
					this.SendPropertyChanged("Klijent_serija");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Serija_Klijent_serija1", Storage="_Klijent_serijas", ThisKey="ID", OtherKey="IDserije")]
		public EntitySet<Klijent_serija> Klijent_serijas
		{
			get
			{
				return this._Klijent_serijas;
			}
			set
			{
				this._Klijent_serijas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Glumci_Serija", Storage="_Glumci1", ThisKey="ID", OtherKey="ID", IsForeignKey=true)]
		public Glumci Glumci1
		{
			get
			{
				return this._Glumci1.Entity;
			}
			set
			{
				Glumci previousValue = this._Glumci1.Entity;
				if (((previousValue != value) 
							|| (this._Glumci1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Glumci1.Entity = null;
						previousValue.Serija = null;
					}
					this._Glumci1.Entity = value;
					if ((value != null))
					{
						value.Serija = this;
						this._ID = value.ID;
					}
					else
					{
						this._ID = default(int);
					}
					this.SendPropertyChanged("Glumci1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Osoblje_Serija", Storage="_Osoblje1", ThisKey="ID", OtherKey="ID", IsForeignKey=true)]
		public Osoblje Osoblje1
		{
			get
			{
				return this._Osoblje1.Entity;
			}
			set
			{
				Osoblje previousValue = this._Osoblje1.Entity;
				if (((previousValue != value) 
							|| (this._Osoblje1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Osoblje1.Entity = null;
						previousValue.Serija = null;
					}
					this._Osoblje1.Entity = value;
					if ((value != null))
					{
						value.Serija = this;
						this._ID = value.ID;
					}
					else
					{
						this._ID = default(int);
					}
					this.SendPropertyChanged("Osoblje1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Klijent_serijas(Klijent_serija entity)
		{
			this.SendPropertyChanging();
			entity.Serija1 = this;
		}
		
		private void detach_Klijent_serijas(Klijent_serija entity)
		{
			this.SendPropertyChanging();
			entity.Serija1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Glumci")]
	public partial class Glumci : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _ime;
		
		private string _prezime;
		
		private EntityRef<Serija> _Serija;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnimeChanging(string value);
    partial void OnimeChanged();
    partial void OnprezimeChanging(string value);
    partial void OnprezimeChanged();
    #endregion
		
		public Glumci()
		{
			this._Serija = default(EntityRef<Serija>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ime", DbType="NVarChar(MAX)")]
		public string ime
		{
			get
			{
				return this._ime;
			}
			set
			{
				if ((this._ime != value))
				{
					this.OnimeChanging(value);
					this.SendPropertyChanging();
					this._ime = value;
					this.SendPropertyChanged("ime");
					this.OnimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prezime", DbType="NVarChar(MAX)")]
		public string prezime
		{
			get
			{
				return this._prezime;
			}
			set
			{
				if ((this._prezime != value))
				{
					this.OnprezimeChanging(value);
					this.SendPropertyChanging();
					this._prezime = value;
					this.SendPropertyChanged("prezime");
					this.OnprezimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Glumci_Serija", Storage="_Serija", ThisKey="ID", OtherKey="ID", IsUnique=true, IsForeignKey=false)]
		public Serija Serija
		{
			get
			{
				return this._Serija.Entity;
			}
			set
			{
				Serija previousValue = this._Serija.Entity;
				if (((previousValue != value) 
							|| (this._Serija.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Serija.Entity = null;
						previousValue.Glumci1 = null;
					}
					this._Serija.Entity = value;
					if ((value != null))
					{
						value.Glumci1 = this;
					}
					this.SendPropertyChanged("Serija");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Klijent_serija")]
	public partial class Klijent_serija : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _IDserije;
		
		private string _Ime;
		
		private string _Glumci;
		
		private string _Osoblje;
		
		private string _Opis;
		
		private string _Pogledano_epizoda;
		
		private EntityRef<Serija> _Serija;
		
		private EntityRef<Serija> _Serija1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnIDserijeChanging(int value);
    partial void OnIDserijeChanged();
    partial void OnImeChanging(string value);
    partial void OnImeChanged();
    partial void OnGlumciChanging(string value);
    partial void OnGlumciChanged();
    partial void OnOsobljeChanging(string value);
    partial void OnOsobljeChanged();
    partial void OnOpisChanging(string value);
    partial void OnOpisChanged();
    partial void OnPogledano_epizodaChanging(string value);
    partial void OnPogledano_epizodaChanged();
    #endregion
		
		public Klijent_serija()
		{
			this._Serija = default(EntityRef<Serija>);
			this._Serija1 = default(EntityRef<Serija>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					if (this._Serija.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDserije", DbType="Int NOT NULL")]
		public int IDserije
		{
			get
			{
				return this._IDserije;
			}
			set
			{
				if ((this._IDserije != value))
				{
					if (this._Serija1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDserijeChanging(value);
					this.SendPropertyChanging();
					this._IDserije = value;
					this.SendPropertyChanged("IDserije");
					this.OnIDserijeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ime", DbType="NVarChar(MAX)")]
		public string Ime
		{
			get
			{
				return this._Ime;
			}
			set
			{
				if ((this._Ime != value))
				{
					this.OnImeChanging(value);
					this.SendPropertyChanging();
					this._Ime = value;
					this.SendPropertyChanged("Ime");
					this.OnImeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Glumci", DbType="NVarChar(MAX)")]
		public string Glumci
		{
			get
			{
				return this._Glumci;
			}
			set
			{
				if ((this._Glumci != value))
				{
					this.OnGlumciChanging(value);
					this.SendPropertyChanging();
					this._Glumci = value;
					this.SendPropertyChanged("Glumci");
					this.OnGlumciChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Osoblje", DbType="NVarChar(MAX)")]
		public string Osoblje
		{
			get
			{
				return this._Osoblje;
			}
			set
			{
				if ((this._Osoblje != value))
				{
					this.OnOsobljeChanging(value);
					this.SendPropertyChanging();
					this._Osoblje = value;
					this.SendPropertyChanged("Osoblje");
					this.OnOsobljeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Opis", DbType="NVarChar(MAX)")]
		public string Opis
		{
			get
			{
				return this._Opis;
			}
			set
			{
				if ((this._Opis != value))
				{
					this.OnOpisChanging(value);
					this.SendPropertyChanging();
					this._Opis = value;
					this.SendPropertyChanged("Opis");
					this.OnOpisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pogledano_epizoda", DbType="NVarChar(MAX)")]
		public string Pogledano_epizoda
		{
			get
			{
				return this._Pogledano_epizoda;
			}
			set
			{
				if ((this._Pogledano_epizoda != value))
				{
					this.OnPogledano_epizodaChanging(value);
					this.SendPropertyChanging();
					this._Pogledano_epizoda = value;
					this.SendPropertyChanged("Pogledano_epizoda");
					this.OnPogledano_epizodaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Serija_Klijent_serija", Storage="_Serija", ThisKey="ID", OtherKey="ID", IsForeignKey=true)]
		public Serija Serija
		{
			get
			{
				return this._Serija.Entity;
			}
			set
			{
				Serija previousValue = this._Serija.Entity;
				if (((previousValue != value) 
							|| (this._Serija.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Serija.Entity = null;
						previousValue.Klijent_serija = null;
					}
					this._Serija.Entity = value;
					if ((value != null))
					{
						value.Klijent_serija = this;
						this._ID = value.ID;
					}
					else
					{
						this._ID = default(int);
					}
					this.SendPropertyChanged("Serija");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Serija_Klijent_serija1", Storage="_Serija1", ThisKey="IDserije", OtherKey="ID", IsForeignKey=true)]
		public Serija Serija1
		{
			get
			{
				return this._Serija1.Entity;
			}
			set
			{
				Serija previousValue = this._Serija1.Entity;
				if (((previousValue != value) 
							|| (this._Serija1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Serija1.Entity = null;
						previousValue.Klijent_serijas.Remove(this);
					}
					this._Serija1.Entity = value;
					if ((value != null))
					{
						value.Klijent_serijas.Add(this);
						this._IDserije = value.ID;
					}
					else
					{
						this._IDserije = default(int);
					}
					this.SendPropertyChanged("Serija1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Osoblje")]
	public partial class Osoblje : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Ime;
		
		private string _Prezime;
		
		private string _Tvrtka;
		
		private EntityRef<Serija> _Serija;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnImeChanging(string value);
    partial void OnImeChanged();
    partial void OnPrezimeChanging(string value);
    partial void OnPrezimeChanged();
    partial void OnTvrtkaChanging(string value);
    partial void OnTvrtkaChanged();
    #endregion
		
		public Osoblje()
		{
			this._Serija = default(EntityRef<Serija>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ime", DbType="NVarChar(MAX)")]
		public string Ime
		{
			get
			{
				return this._Ime;
			}
			set
			{
				if ((this._Ime != value))
				{
					this.OnImeChanging(value);
					this.SendPropertyChanging();
					this._Ime = value;
					this.SendPropertyChanged("Ime");
					this.OnImeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prezime", DbType="NVarChar(MAX)")]
		public string Prezime
		{
			get
			{
				return this._Prezime;
			}
			set
			{
				if ((this._Prezime != value))
				{
					this.OnPrezimeChanging(value);
					this.SendPropertyChanging();
					this._Prezime = value;
					this.SendPropertyChanged("Prezime");
					this.OnPrezimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tvrtka", DbType="NVarChar(MAX)")]
		public string Tvrtka
		{
			get
			{
				return this._Tvrtka;
			}
			set
			{
				if ((this._Tvrtka != value))
				{
					this.OnTvrtkaChanging(value);
					this.SendPropertyChanging();
					this._Tvrtka = value;
					this.SendPropertyChanged("Tvrtka");
					this.OnTvrtkaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Osoblje_Serija", Storage="_Serija", ThisKey="ID", OtherKey="ID", IsUnique=true, IsForeignKey=false)]
		public Serija Serija
		{
			get
			{
				return this._Serija.Entity;
			}
			set
			{
				Serija previousValue = this._Serija.Entity;
				if (((previousValue != value) 
							|| (this._Serija.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Serija.Entity = null;
						previousValue.Osoblje1 = null;
					}
					this._Serija.Entity = value;
					if ((value != null))
					{
						value.Osoblje1 = this;
					}
					this.SendPropertyChanged("Serija");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
