#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplikacijaGUI
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Glumci> Glumcis
		{
			get
			{
				return this.GetTable<Glumci>();
			}
		}
		
		public System.Data.Linq.Table<Osoblje> Osobljes
		{
			get
			{
				return this.GetTable<Osoblje>();
			}
		}
		
		public System.Data.Linq.Table<Serija> Serijas
		{
			get
			{
				return this.GetTable<Serija>();
			}
		}
		
		public System.Data.Linq.Table<Klijent_serija> Klijent_serijas
		{
			get
			{
				return this.GetTable<Klijent_serija>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class Glumci
	{
		
		private string _ID;
		
		private string _ime;
		
		private string _prezime;
		
		public Glumci()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", CanBeNull=false)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ime", CanBeNull=false)]
		public string ime
		{
			get
			{
				return this._ime;
			}
			set
			{
				if ((this._ime != value))
				{
					this._ime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prezime", CanBeNull=false)]
		public string prezime
		{
			get
			{
				return this._prezime;
			}
			set
			{
				if ((this._prezime != value))
				{
					this._prezime = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class Osoblje
	{
		
		private string _ID;
		
		private string _Ime;
		
		private string _Prezime;
		
		private string _Tvrtka;
		
		public Osoblje()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", CanBeNull=false)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ime", CanBeNull=false)]
		public string Ime
		{
			get
			{
				return this._Ime;
			}
			set
			{
				if ((this._Ime != value))
				{
					this._Ime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prezime", CanBeNull=false)]
		public string Prezime
		{
			get
			{
				return this._Prezime;
			}
			set
			{
				if ((this._Prezime != value))
				{
					this._Prezime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tvrtka", CanBeNull=false)]
		public string Tvrtka
		{
			get
			{
				return this._Tvrtka;
			}
			set
			{
				if ((this._Tvrtka != value))
				{
					this._Tvrtka = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class Serija
	{
		
		private string _ID;
		
		private string _Ime;
		
		private string _Glumci;
		
		private string _Osoblje;
		
		private string _Opis;
		
		public Serija()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", CanBeNull=false)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ime", CanBeNull=false)]
		public string Ime
		{
			get
			{
				return this._Ime;
			}
			set
			{
				if ((this._Ime != value))
				{
					this._Ime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Glumci", CanBeNull=false)]
		public string Glumci
		{
			get
			{
				return this._Glumci;
			}
			set
			{
				if ((this._Glumci != value))
				{
					this._Glumci = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Osoblje", CanBeNull=false)]
		public string Osoblje
		{
			get
			{
				return this._Osoblje;
			}
			set
			{
				if ((this._Osoblje != value))
				{
					this._Osoblje = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Opis", CanBeNull=false)]
		public string Opis
		{
			get
			{
				return this._Opis;
			}
			set
			{
				if ((this._Opis != value))
				{
					this._Opis = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class Klijent_serija
	{
		
		private string _ID;
		
		private string _IDserije;
		
		private string _Ime;
		
		private string _Glumci;
		
		private string _Osoblje;
		
		private string _Opis;
		
		private string _Pogledano_epizoda;
		
		public Klijent_serija()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", CanBeNull=false)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDserije", CanBeNull=false)]
		public string IDserije
		{
			get
			{
				return this._IDserije;
			}
			set
			{
				if ((this._IDserije != value))
				{
					this._IDserije = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ime", CanBeNull=false)]
		public string Ime
		{
			get
			{
				return this._Ime;
			}
			set
			{
				if ((this._Ime != value))
				{
					this._Ime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Glumci", CanBeNull=false)]
		public string Glumci
		{
			get
			{
				return this._Glumci;
			}
			set
			{
				if ((this._Glumci != value))
				{
					this._Glumci = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Osoblje", CanBeNull=false)]
		public string Osoblje
		{
			get
			{
				return this._Osoblje;
			}
			set
			{
				if ((this._Osoblje != value))
				{
					this._Osoblje = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Opis", CanBeNull=false)]
		public string Opis
		{
			get
			{
				return this._Opis;
			}
			set
			{
				if ((this._Opis != value))
				{
					this._Opis = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pogledano_epizoda", CanBeNull=false)]
		public string Pogledano_epizoda
		{
			get
			{
				return this._Pogledano_epizoda;
			}
			set
			{
				if ((this._Pogledano_epizoda != value))
				{
					this._Pogledano_epizoda = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
